### PR TITLE
Add show type at point command

### PR DESCRIPTION
**Pull request by jedahu**
I find eldoc slows things down too much. Here is a simple alternative.

### CODE REVIEW

**Comment by jdelStrother** [comment]
Have you just disabled the eldoc package in your .spacemacs file?   Maybe I should add a configuration setting to disable the eldoc/flow integration.

**Comment by jedahu** [comment]
Yes, just in my .spacemacs. A setting would probably be a good idea.

**Comment by jdelStrother** [comment]
I've cherry-picked this and added a configuration variable.   If you'd like to disable the automatic eldoc integration, try this in your .spacemacs:

```emacs
dotspacemacs-configuration-layers
  '(
    (flow-type :variables flow-type-enable-eldoc-type-info nil)
```

Thanks for the PR!

**Comment by jedahu** [comment]
Great. I'll update my .spacemacs.

**Pull request closed without merging**
